# Generated by Django 6.0.4 on 2026-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_product_availability_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='unisex', max_length=200, null=True),
        ),
    ]
